project_name: development-env
builds:
  - main: ./cmd/main.go
    goos:
      - linux
      - darwin
      #- windows
    goarch:
      - amd64
      - arm64
    ldflags: -s -w
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ .ProjectName }}_{{ .Version }}_snapshot"
